# Generated by Django 3.1.5 on 2021-01-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthUser',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('site', models.CharField(choices=[('Google', 'Google'), ('GitHub', 'GitHub'), ('LinkedIn', 'LinkedIn'), ('Indeed', 'Indeed')], max_length=24)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
