name: Run Python Tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run tests with pytest
        run: pipenv run pytest
